name: CmdSnooper
main: cmdsnooper\CmdSnooper
version: 1.2.1
api: 3.6.5
author: HotshotHD
description: Spy on players to see what commands are being ran

commands:
  snoop:
    description: Enter snoop mode
permissions:
   snoop.command:
    default: op
